dependencies:
  - name: em-stitching
    version: ~0.0.1
    repository: '@hmcts'

  - name: em-ccd-orchestrator
    version: ~0.0.1
    repository: '@hmcts'

#   DEPENDENCIES
  - name: rpe-service-auth-provider
    version: ~0.0.2
    repository: '@hmcts'

  - name: dm-store
    version: ~1.0.0
    repository: '@hmcts'

  - name: postgresql
    version: ~3.1.0
    repository: '@stable'

#  - Should I skip IDAM? Yes, no supported IDAM docker images.
#  - Should I skip smtp-server? Yes, probably.
#  - IDAM might use it, but we're using SAAT idam, so we don't care if it uses it.
