# If a service wants to use us, they'd add this product chart to requirements.yaml.
# Then they could override em-anno microservice chart to add their team to the s2s whitelist.
# Note that this would go in their product chart, not this one.

global:
  environment: demo
  subscriptionId: "bf308a5c-0624-4334-8ff8-8dca9fd43783"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

tags:
  postgresql-pod: false                 # any chart specific postgres
  blobstorage: false                     # blob storage for dm-store

postgresql:
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE USER evidence WITH PASSWORD 'evidence';
      CREATE DATABASE evidence WITH OWNER = evidence ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE USER emstitch WITH PASSWORD 'emstitch';
      CREATE DATABASE emstitch WITH OWNER = emstitch ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  nameOverride: postgres-db
  persistence:
    enabled: false

### EM SERVICES ###
em-stitching:
  stitching:
    releaseNameOverride: chart-em-bundling-release-em-stitching
    image: hmctspublic.azurecr.io/em/stitching:latest
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://chart-em-bundling-release-postgres-db:5432/postgres?ssl=disable'
      S2S_BASE_URI: http://chart-em-bundling-release-rpe-s2s
      DM_STORE_APP_URL: http://chart-em-bundling-release-dm-store
      IDAM_API_BASE_URI: https://idam-api.demo.platform.hmcts.net

em-ccd-orchestrator:
  ccd-orchestrator:
    image: hmctspublic.azurecr.io/em/ccd-orchestrator:latest
    environment:
      EM_STITCHING_API_URL: http://chart-em-bundling-release-em-stitching
      S2S_BASE_URI: http://chart-em-bundling-release-rpe-s2s
      DM_STORE_APP_URL: http://chart-em-bundling-release-dm-store
      IDAM_API_BASE_URI: https://idam-api.demo.platform.hmcts.net

###### DEPENDENCIES #####
rpe-service-auth-provider:
  java:
    releaseNameOverride: chart-em-bundling-release-rpe-s2s
    image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest

dm-store:
  java:
    releaseNameOverride: chart-em-bundling-release-dm-store
    image: hmctspublic.azurecr.io/dm/store:latest
    secrets:
      STORAGE_ACCOUNT_NAME:
        disabled: true
      STORAGE_ACCOUNT_KEY:
        disabled: true
      STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:
        disabled: true
    keyVaults:
    environment:
      ENABLE_DB_MIGRATE: 'true'
      ENABLE_TTL: 'false'
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      ENABLE_AZURE_STORAGE_CONTAINER: 'false'
      POSTGRES_STORAGE_ENABLED: 'true'
      CCD_DM_STORE_STORAGE_ACC_PRIMARY_CONN_STRING: 'dm-store-storage-account-primary-connection-string'
      CCD_DM_STORE_STORAGE_ACC_SECONDARY_CONN_STRING: 'dm-store-storage-account-secondary-connection-string'