# If a service wants to use us, they'd add this product chart to requirements.yaml.
# Then they could override em-anno microservice chart to add their team to the s2s whitelist.
# Note that this would go in their product chart, not this one.

global:
  environment: saat
  subscriptionId: "bf308a5c-0624-4334-8ff8-8dca9fd43783"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

### EM SERVICES ###
em-stitching:
  em-stitching:
    image: hmcts.azurecr.io/hmcts/em-stitching:latest
    readinessDelay: 40
    readinessTimeout: 20
    readinessFailureThreshold: 20
    readinessPeriod: 15
    livenessDelay: 40
    livenessTimeout: 20
    livenessPeriod: 15
    livenessFailureThreshold: 20
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chart-em-bundling-release-rpa-em-stitching-db:5432/emstitch?ssl=disable
      IDAM_API_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
      S2S_BASE_URI: http://chart-em-bundling-release-rpe-service-auth-provider
      DM_STORE_APP_URL: http://dm-store-saat.service.core-compute-saat.internal
      DOCMOSIS_ENDPOINT: https://docmosis-development.platform.hmcts.net/rs/convert

em-ccd-orchestrator:
  ccd-orchestrator:
    image: hmcts.azurecr.io/hmcts/em-ccd-orchestrator:latest
    readinessDelay: 40
    readinessTimeout: 20
    readinessFailureThreshold: 20
    readinessPeriod: 15
    livenessDelay: 40
    livenessTimeout: 20
    livenessPeriod: 15
    livenessFailureThreshold: 20
    environment:
      EM_STITCHING_API_URL: http://chart-em-bundling-release-em-stitching
      IDAM_API_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
      S2S_BASE_URI: http://chart-em-bundling-release-rpe-service-auth-provider
      DM_STORE_APP_URL: http://dm-store-saat.service.core-compute-saat.internal

###### DEPENDENCIES #####
rpe-service-auth-provider:
  java:
    releaseNameOverride: chart-em-bundling-release-rpe-service-auth-provider
    image: hmcts.azurecr.io/hmcts/rpe-service-auth-provider:latest

#dm-store:
#  java:
#    releaseNameOverride: dm-store
#    image: hmcts.azurecr.io/hmcts/dm-store:latest
#    environment:
#      IDAM_USER_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
#      IDAM_S2S_BASE_URI: http://rpe-service-auth-provider
#    secrets:
#      STORAGE_ACCOUNT_NAME:
#        secretRef: storage-secret-em-annotation
#        key: storageAccountName
#        STORAGE_ACCOUNT_KEY:
#          secretRef: storage-secret-em-annotation
#          key: accessKey
#        STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:
#          secretRef: container-secret-em-annotation-dm-docstore
#          key: containerName
